(async()=>{
 const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
 const browser=await require('playwright').chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const url=process.env.CCA_LAB_TEST_URL||'http://127.0.0.1:8099';
 const call=(path,method='GET',body)=>page.evaluate(async({path,method,body})=>accountAPI(path,method,body),{path,method,body});
 const poll=async fn=>{for(let i=0;i<240;i++){if(await fn())return;await new Promise(r=>setTimeout(r,250));}throw Error('Background operation timed out');};
 const login=async(name,password)=>{await page.goto(url);await page.locator('#sign-in-form [name=username]').fill(name);await page.locator('#sign-in-form [name=password]').fill(password);await page.locator('#sign-in-form [value=login]').click();await page.waitForFunction(()=>accountState.ready&&document.body.classList.contains('signed-in'));};
 await page.goto(url);await page.waitForSelector('#login-panel');
 assert.equal(await page.locator('main').isVisible(),false);
 await login('admin','browser-password-1234');
 await page.locator('#manage-users').click();await page.locator('#admin-create-user [name=username]').fill('staffer');await page.locator('#admin-create-user [name=password]').fill('staffer-password-1234');await page.locator('#admin-create-user button').click();await page.waitForFunction(()=>document.querySelector('#account-content').textContent.includes('staffer'));await page.locator('#account-close').click();
 const original=await page.evaluate(()=>accountState.project.id);
 await page.locator('#new-project').click();await page.locator('#create-project input').fill('Research team');await page.locator('#create-project button').click();
 await page.waitForFunction(()=>accountState.ready&&accountState.project.name==='Research team');
 const project=await page.evaluate(()=>accountState.project.id);assert.notEqual(project,original);
 await call('/auth/register','POST',{username:'reader',password:'reader-password-1234'});
 await page.locator('#manage-members').click();await page.locator('#add-member [name=username]').fill('reader');await page.locator('#add-member [name=role]').selectOption('view');await page.locator('#add-member button').click();
 await page.waitForFunction(()=>document.querySelector('#account-content').textContent.includes('reader'));
 await page.screenshot({path:(process.env.CCA_LAB_SCREENSHOT_DIR||'/tmp')+'/project-members.png'});await page.locator('#account-close').click();
 const codebook=JSON.parse(fs.readFileSync(path.join(__dirname,'../examples/task_multi.cca.json'),'utf8'));
 codebook.task.categories=[{id:'A',label:'Alpha',definition:'Alpha category'},{id:'B',label:'Beta',definition:'Beta category'}];codebook.examples=[];
 const task=await call('/tasks','POST',{codebook});
 const dataset=await page.evaluate(async()=>{const r=await fetch('/api/datasets?filename=gold.csv',{method:'POST',body:'doc_id,text,gold_label\n1,Alpha,A\n2,Beta,B\n'});if(!r.ok)throw Error(await r.text());return r.json();});
 await poll(async()=>(await call('/datasets')).some(d=>d.id===dataset.id&&d.status==='ready'&&d.total===2));
 const profile=await call('/profiles','POST',{name:'Mock',provider:'mock'});
 const gold=await call('/gold-sets','POST',{name:'Gold',dataset_id:dataset.id,mode:'multi',allow_empty:true});
 const evaluation=await call('/evaluations','POST',{name:'Project evaluation',task_id:task.id,gold_id:gold.id,variants:[{name:'Mock',profile_id:profile.id,query:{model:'mock'}}]});
 await poll(async()=>(await call('/evaluations/'+evaluation.id)).report_ready);
 await page.evaluate(()=>{location.hash='evaluations';return refresh();});await page.locator('[data-action=evaluation-detail]').click();await page.waitForSelector('#evaluation-summary');
 const link=page.locator('a[href*="export-predictions"][href*="format=csv"]');assert.ok((await link.getAttribute('href')).includes('project_id='+project));
 const download=page.waitForEvent('download');await link.click();assert.ok(fs.readFileSync(await (await download).path(),'utf8').includes('Alpha'));
 await page.locator('[data-action=close-detail]').click();await page.locator('#project-selector').selectOption(original);await page.waitForFunction(id=>accountState.ready&&accountState.project.id===id,original);
 assert.equal((await call('/tasks')).length,0);
 await page.locator('#logout').click();await page.waitForSelector('#login-panel');await login('reader','reader-password-1234');
 await page.waitForFunction(()=>accountState.project?.role==='view');
 assert.equal(await page.locator('#primary').isVisible(),false);assert.equal(await page.locator('#manage-members').isVisible(),false);assert.equal(await page.locator('#manage-users').isVisible(),false);
 const status=await page.evaluate(async task=>(await fetch('/api/tasks/'+task,{method:'DELETE'})).status,task.id);assert.equal(status,403);
 await page.screenshot({path:(process.env.CCA_LAB_SCREENSHOT_DIR||'/tmp')+'/project-reader.png'});
 assert.deepEqual(errors,[]);
 console.log('PASS accounts browser: sign in/out, create/switch project, members, read-only UI, isolated data, project worker evaluation, scoped CSV download');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
