const {chromium}=require('playwright');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=500)errors.push(r.status()+' '+r.url())});
 const poll=async fn=>{for(let i=0;i<150;i++){if(await fn())return;await new Promise(r=>setTimeout(r,200));}throw Error('Background operation timed out');};
 const post=async(path,data)=>{const r=await page.request.post((process.env.TEXTLAB_TEST_URL||'http://127.0.0.1:8099')+'/api'+path,{data:typeof data==='string'?Buffer.from(data):data});if(!r.ok())throw Error(await r.text());return r.json()};
 await page.goto((process.env.TEXTLAB_TEST_URL||'http://127.0.0.1:8099'));await page.waitForFunction(()=>document.querySelector('#title').textContent==='Define tasks');
 if(await page.locator('nav[aria-label="Research workflow"] a').count()!==5)throw Error('Workflow must have 5 steps');
 if(await page.locator('.config-section a[href="#profiles"]').count()!==1)throw Error('Missing separate config');

 const doc={"$schema":"https://cca-schema.org/schema/0.1/schema.json",id:"sentiment",version:"1.0.0",title:"CCA sentiment",description:"Sentiment of a sentence",authors:["Research team"],language:"en",task:{instructions:"Apply the criteria.",unit_of_analysis:"sentence",classification_mode:"single_label",context:"Resolve speaker attribution.",categories:[{id:"101",label:"Positive",definition:"Favorable tone",inclusion_criteria:["Explicit praise"],exclusion_criteria:["Irony"],coding_notes:"Identify the speaker.",aliases:["pos"]},{id:"102",label:"Negative",definition:"Unfavorable tone"}]},examples:[{text:"Wonderful",labels:["101"],context:"A successful outcome",explanation:"Explicit approval"}]};
 // Actual picker, with two forced background refreshes while it is open.
 const pickerPromise=page.waitForEvent('filechooser');
 await page.locator('[data-action=cca-import]').click();
 const picker=await pickerPromise;
 await page.evaluate(async()=>{await refresh();await refresh();});
 if(!await picker.element().evaluate(el=>el.isConnected))throw Error('Picker detached during refresh');
 await picker.setFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{}')});
 await page.waitForFunction(()=>document.querySelector('#cca-import-status').textContent.includes('CCA import:'));
 if((await page.request.get((process.env.TEXTLAB_TEST_URL||'http://127.0.0.1:8099')+'/api/tasks').then(r=>r.json())).length)throw Error('Invalid import created task');
 await page.evaluate(async()=>{await refresh();});
 if(!(await page.locator('#cca-import-status').innerText()).includes('CCA import:'))throw Error('Error disappeared on refresh');
 const second=page.waitForEvent('filechooser');await page.locator('[data-action=cca-import]').click();
 const validPicker=await second;await page.evaluate(async()=>{await refresh();await refresh();});
 await validPicker.setFiles({name:'sentiment.cca.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});
 await page.waitForFunction(()=>document.querySelector('#editor').open&&document.querySelector('[name=title]').value==='CCA sentiment');

 if(await page.locator('[name=unit_of_analysis]').inputValue()!=='sentence')throw Error('Missing unit');
 await page.locator('[name=title]').fill('Edited CCA sentiment');
 await page.getByText('Criteria, aliases and coding notes',{exact:true}).first().click();
 await page.locator('.cca-category').first().locator('[data-key=inclusion_criteria] [data-action=cca-add-item]').click();
 await page.locator('.cca-category').first().locator('[data-key=inclusion_criteria] textarea').last().fill('Positive evaluation');
 await page.locator('#editor-form button[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#editor').open);
 const downloadPromise=page.waitForEvent('download');await page.locator('[data-action=cca-export]').click();const download=await downloadPromise;
 const path=await download.path();const exported=JSON.parse(fs.readFileSync(path,'utf8'));
 if(exported.title!=='Edited CCA sentiment'||exported.authors[0]!=='Research team'||exported.task.categories[0].id!=='101'||exported.task.categories[0].label!=='Positive'||exported.task.categories[0].inclusion_criteria.length!==2||exported.examples[0].context!==doc.examples[0].context)throw Error('Roundtrip lost metadata/edits');
 await page.locator('[data-action=edit-task]').click();await page.getByText('Prompt preview',{exact:true}).click();await page.locator('[data-action=prompt-preview]').click();
 await page.waitForFunction(()=>document.querySelector('#prompt-preview').textContent.includes('Positive evaluation'));
 if(!(await page.locator('#prompt-preview').innerText()).includes('Resolve speaker attribution'))throw Error('Missing prompt context');
 await page.locator('[data-action=close]').first().click();

 await page.locator('#primary').click();
 if(await page.locator('[name=title]').inputValue()!=='')throw Error('Creation should start blank');
 if(await page.locator('[name=ambiguity_rule]').count())throw Error('Legacy ambiguity field remains');
 if(await page.locator('#editor-body').innerText().then(t=>t.includes('Fixed output order:')))throw Error('Removed help remains');
 if(await page.locator('[data-action=prompt-preview]').isVisible())throw Error('Preview should start collapsed');
 await page.locator('[name=title]').fill('Fresh CCA task');
 await page.locator('[name=description]').fill('A new coding instrument');
 await page.locator('[name=instructions]').fill('Apply the inclusion criteria.');
 await page.locator('[name=cat-id]').fill('positive');
 await page.locator('[name=cat-label]').fill('Positive');
 await page.locator('[name=cat-definition]').fill('Favorable evaluation');
 await page.locator('[data-action=add-category]').click();
 await page.locator('[name=cat-id]').last().fill('positive');
 await page.locator('[name=cat-label]').last().fill('Negative');
 await page.locator('[name=cat-definition]').last().fill('Unfavorable evaluation');
 await page.locator('#editor-form button[type=submit]').click();
 await page.waitForFunction(()=>document.querySelector('[name=cat-id][aria-invalid=true]'));
 if(!(await page.locator('.cca-field-error').innerText()).includes('unique'))throw Error('Missing category field error');
 await page.locator('[name=cat-id]').last().fill('negative');
 await page.locator('[data-action=cca-add-example]').click();
 await page.locator('[name=example_text]').fill('Wonderful!');
 await page.locator('[name=example_labels]').selectOption('positive');
 await page.locator('[name=explanation]').fill('Explicit praise');
 await page.getByText('TextLab execution defaults',{exact:true}).click();
 await page.locator('[name=default_label]').selectOption('negative');
 await page.locator('[name=evidence]').check();
 await page.locator('#editor-form button[type=submit]').click();
 await page.waitForFunction(()=>!document.querySelector('#editor').open);
 const tasks=await page.request.get((process.env.TEXTLAB_TEST_URL||'http://127.0.0.1:8099')+'/api/tasks').then(r=>r.json());
 const fresh=tasks.find(t=>t.spec.codebook.title==='Fresh CCA task');
 if(!fresh||fresh.spec.execution_defaults.default_label!=='negative'||fresh.spec.codebook.examples[0].labels[0]!=='positive')throw Error('Fresh task not stored canonically');
 const nativeDownload=page.waitForEvent('download');await page.locator('[data-action=download-task][data-id="'+fresh.id+'"]').click();
 const native=JSON.parse(fs.readFileSync(await (await nativeDownload).path(),'utf8'));
 if(!native.codebook||!native.execution_defaults||native.name)throw Error('Native export incorrect');
 await page.locator('[data-action=edit-task][data-id="'+fresh.id+'"]').click();
 await page.waitForTimeout(200);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);

 await page.locator('[data-action=close]').first().click();
 await page.setViewportSize({width:1440,height:1050});
 const profile=await post('/profiles',{name:'Demo',provider:'mock',base_url:'http://localhost'});
 const dataset=await page.evaluate(async csv=>{const r=await fetch('/api/datasets?filename=gold.csv',{method:'POST',body:csv});if(!r.ok)throw Error(await r.text());return r.json();},['doc_id,text,gold_label','1,Wonderful,positive','2,Poor,negative',''].join(String.fromCharCode(10)));
 await poll(async()=>(await page.request.get((process.env.TEXTLAB_TEST_URL||'http://127.0.0.1:8099')+'/api/datasets').then(r=>r.json())).find(d=>d.id===dataset.id)?.status==='ready');
 const gold=await post('/gold-sets',{name:'Gold',dataset_id:dataset.id,doc_id_column:'doc_id',text_column:'text',gold_column:'gold_label'});
 const evaluation=await post('/evaluations',{name:'CCA check',task_id:fresh.id,gold_id:gold.id,seeds:[1,2],variants:[{name:'Demo',profile_id:profile.id,query:{model:'mock'}}]});
 await poll(async()=>(await page.request.get((process.env.TEXTLAB_TEST_URL||'http://127.0.0.1:8099')+'/api/evaluations/'+evaluation.id).then(r=>r.json())).report_ready);
 await page.evaluate(async()=>{await refresh();location.hash='evaluations';});
 await page.locator('[data-action=evaluation-detail]').click();
 await page.waitForSelector('#evaluation-report table');
 if(!(await page.locator('#evaluation-report').innerText()).includes('positive'))throw Error('Evaluation did not use category IDs');
 await page.locator('[data-action=close-detail]').click();
 await page.evaluate(()=>location.hash='prediction');
 await page.locator('#primary').click();
 await page.locator('[name=task_ids]').selectOption(fresh.id);
 await page.locator('[name=model]').fill('mock');
 await page.locator('[name=name]').fill('CCA prediction');
 await page.locator('#editor-form button[type=submit]').click();
 await page.waitForFunction(()=>!document.querySelector('#editor').open);
 await poll(async()=>(await page.request.get((process.env.TEXTLAB_TEST_URL||'http://127.0.0.1:8099')+'/api/predictions').then(r=>r.json())).some(p=>p.artifact_status==='ready'));
 await page.evaluate(async()=>{await refresh();});
 await page.locator('[data-action=prediction-detail]').click();
 await page.waitForSelector('#detail-body a[href*="/download/csv"]');
 if(!(await page.locator('#detail-body').innerText()).includes('Fresh CCA task'))throw Error('Prediction task title missing');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS: schema-first create/edit/field errors/native export/evaluation/prediction; real file picker survives refresh; invalid file shows persistent error; CCA file import; editable criteria/context; metadata and category IDs preserved after save/export; prompt includes criteria and context; download works; no JS/HTTP5xx errors.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
